version: "3.9"
services:
  neo:
    build:
      context: .
      args:
        - GIT_SHA=${GIT_SHA:-DEV}
    image: project-neo-intake:dev
    container_name: neo-intake-dev
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./:/app
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

