"""JSON Schema and required-keys map for the 20 GEN2 packs.

This module intentionally defines only top-level requirements to avoid drift
and keep CI stable. It can be extended with deeper property types later.
"""

from __future__ import annotations

from typing import Dict, List


def required_keys_map() -> Dict[str, List[str]]:
    return {
            "01_README+Directory-Map_v2.json": [
                    "contracts",
                    "conventions",
                    "dependency_map",
                    "files",
                    "getting_started",
                    "meta",
                    "naming",
                    "objective",
                    "structure_map",
                    "token_budget",
                    "update_policy",
                    "version"
            ],
            "02_Global-Instructions_v2.json": [
                    "agentic_policies",
                    "archetypes",
                    "constraints",
                    "context",
                    "defaults",
                    "effective_autonomy",
                    "go_live",
                    "memory",
                    "meta",
                    "objective",
                    "observability",
                    "references",
                    "refusals",
                    "safety",
                    "store_raw_cot",
                    "time_prefs",
                    "token_budget",
                    "token_hygiene",
                    "version"
            ],
            "03_Operating-Rules_v2.json": [
                    "escalation",
                    "gates",
                    "human_gate",
                    "lifecycle",
                    "logging_audit",
                    "meta",
                    "objective",
                    "rbac",
                    "token_budget",
                    "version"
            ],
            "04_Governance+Risk-Register_v2.json": [
                    "approvals",
                    "classification_default",
                    "compliance_mapping",
                    "controls",
                    "definition_of_done",
                    "definitions",
                    "exceptions",
                    "frameworks",
                    "meta",
                    "objective",
                    "pii_flags",
                    "policy",
                    "privacy_alignment",
                    "reasoning_governance",
                    "regulators",
                    "risk_register",
                    "risk_register_tags",
                    "risk_taxonomy",
                    "scoring_model",
                    "starter_risks",
                    "token_budget",
                    "version",
                    "workflows"
            ],
            "05_Safety+Privacy_Guardrails_v2.json": [
                    "audit_checklist",
                    "content_filters",
                    "data_classification",
                    "jurisdictional_rules",
                    "meta",
                    "no_impersonation",
                    "objective",
                    "operational_hooks",
                    "pii_mask_on_ingest",
                    "principles",
                    "privacy_policies",
                    "redlines",
                    "refusal_playbooks",
                    "token_budget",
                    "version"
            ],
            "06_Role-Recipes_Index_v2.json": [
                    "archetype",
                    "decision_rights",
                    "definition_of_done",
                    "handoffs",
                    "kpis",
                    "mapping",
                    "meta",
                    "objective",
                    "objectives",
                    "role_recipe_ref",
                    "role_title",
                    "roles",
                    "roles_index",
                    "token_budget",
                    "version"
            ],
            "07_Subagent_Role-Recipes_v2.json": [
                    "archetypes",
                    "auto_plan_step",
                    "eval_hooks",
                    "handoffs",
                    "meta",
                    "objective",
                    "planner_builder_evaluator",
                    "reasoning_patterns",
                    "recipes",
                    "token_budget",
                    "version"
            ],
            "08_Memory-Schema_v2.json": [
                    "definition_of_done",
                    "footprint_refs",
                    "hydration",
                    "id",
                    "initial_memory_packs",
                    "memory_scopes",
                    "meta",
                    "objective",
                    "optional_packs",
                    "packs",
                    "permissions",
                    "principles",
                    "quality_controls",
                    "redaction",
                    "retention",
                    "retrieval",
                    "scope_patterns",
                    "scopes",
                    "storage",
                    "stubs",
                    "sync",
                    "token_budget",
                    "types",
                    "version",
                    "writeback_rules"
            ],
            "09_Agent-Manifests_Catalog_v2.json": [
                    "agents",
                    "definition_of_done",
                    "meta",
                    "objective",
                    "owners",
                    "policy",
                    "summary",
                    "token_budget",
                    "version"
            ],
            "10_Prompt-Pack_v2.json": [
                    "guardrails",
                    "meta",
                    "modules",
                    "objective",
                    "output_contracts",
                    "prompts",
                    "reasoning_patterns",
                    "refs",
                    "token_budget",
                    "version"
            ],
            "11_Workflow-Pack_v2.json": [
                    "conventions",
                    "defaults",
                    "engine_adapters",
                    "gates",
                    "graphs",
                    "meta",
                    "micro_loops",
                    "name",
                    "objective",
                    "rollback",
                    "token_budget",
                    "version"
            ],
            "12_Tool+Data-Registry_v2.json": [
                    "connectors",
                    "contracts",
                    "datasets",
                    "definition_of_done",
                    "meta",
                    "objective",
                    "policies",
                    "secrets",
                    "source_registry",
                    "token_budget",
                    "tools",
                    "version"
            ],
            "13_Knowledge-Graph+RAG_Config_v2.json": [
                    "caching",
                    "chunking",
                    "data_quality",
                    "default_index",
                    "definition_of_done",
                    "embeddings",
                    "indexes",
                    "indices",
                    "meta",
                    "objective",
                    "observability",
                    "refs",
                    "rerankers",
                    "retrieval",
                    "retrievers",
                    "safety_overrides",
                    "token_budget",
                    "update_policy",
                    "version"
            ],
            "14_KPI+Evaluation-Framework_v2.json": [
                    "benchmarks",
                    "datasets",
                    "definition_of_done",
                    "eval_cases",
                    "eval_pipelines",
                    "gates",
                    "kpis",
                    "meta",
                    "metrics",
                    "objective",
                    "reasoning_kpis",
                    "refs",
                    "reports",
                    "runner",
                    "suites",
                    "targets",
                    "terms",
                    "token_budget",
                    "version"
            ],
            "15_Observability+Telemetry_Spec_v2.json": [
                    "alerts",
                    "dashboards",
                    "decision_event_field_types",
                    "decision_event_fields",
                    "definition_of_done",
                    "events",
                    "log_schema",
                    "meta",
                    "objective",
                    "pii_redaction",
                    "privacy_controls",
                    "refs",
                    "sampling",
                    "sinks",
                    "storage",
                    "token_budget",
                    "version"
            ],
            "16_Reasoning-Footprints_Schema_v1.json": [
                    "access",
                    "artifacts",
                    "compliance",
                    "decision_factors",
                    "error_taxonomy",
                    "kpi_bindings",
                    "lessons_learned",
                    "meta",
                    "objective",
                    "policy",
                    "rationale_summary",
                    "redaction",
                    "retention",
                    "storage",
                    "store_raw_cot",
                    "token_budget",
                    "version"
            ],
            "17_Lifecycle-Pack_v2.json": [
                    "approvals",
                    "change_log",
                    "change_mgmt",
                    "definition_of_done",
                    "gates",
                    "go_live",
                    "meta",
                    "objective",
                    "refs",
                    "rollback",
                    "stages",
                    "token_budget",
                    "version"
            ],
            "18_Reporting-Pack_v2.json": [
                    "compliance_report",
                    "data_pack",
                    "definition_of_done",
                    "exec_brief",
                    "kpi_views",
                    "meta",
                    "objective",
                    "outputs",
                    "publishing",
                    "refs",
                    "schedule",
                    "templates",
                    "token_budget",
                    "version"
            ],
            "19_Overlay-Pack_SME-Domain_v1.json": [
                    "datasets",
                    "definition_of_done",
                    "eval_cases",
                    "industry",
                    "meta",
                    "naics",
                    "objective",
                    "policies",
                    "prompts",
                    "refs",
                    "region",
                    "regulators",
                    "sector",
                    "standards",
                    "terminology",
                    "token_budget",
                    "version"
            ],
            "20_Overlay-Pack_Enterprise_v1.json": [
                    "brand",
                    "brand_voice",
                    "definition_of_done",
                    "disclaimer",
                    "escalations",
                    "legal",
                    "meta",
                    "objective",
                    "policies",
                    "refs",
                    "stakeholders",
                    "token_budget",
                    "version"
            ]
    }

def _base_properties() -> dict:
    return {
        "meta": {"type": "object"},
        "objective": {"type": ["string", "null"]},
        "schema_keys": {"type": "array", "items": {"type": "string"}},
        "token_budget": {"type": "object"},
    }


def schemas() -> Dict[str, dict]:
    req = required_keys_map()
    out: Dict[str, dict] = {}
    for fname, required in req.items():
        out[fname] = {
            "$schema": "http://json-schema.org/draft-07/schema#",
            "title": fname,
            "type": "object",
            "required": list(required),
            "properties": _base_properties(),
            "additionalProperties": True,
        }
    return out


SCHEMAS: Dict[str, dict] = schemas()

