name: kpi-eval-weekly
on:
  schedule:
    - cron: "0 13 * * MON"
jobs:
  kpi-eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python scripts/run_kpi_eval.py
